### PR TITLE
Fix a few small problems in the forests model

### PR DESCRIPTION
**Pull request by ndw**
In python3, it appears that "" is false, so I fixed a few tests in the constructor.

I also think it's a mistake to throw key errors so I added tests to some of the getters.

### CODE REVIEW

**Comment by paul-hoehne** [comment]
Thank you!  I agree, t would be better to throw key errors when there's no value.

**Comment by ndw** [comment]
"It would be better to" or "it would be better *not* to"?

I'm in favor of returning None rather than throwing an exception, but I can't tell if you're agreeing or disagreeing :-)

**Comment by paul-hoehne** [comment]
Sorry, "not to."  "Man use kompUTER not work gud."

**Comment by paul-hoehne** [comment]
Next time I get some time I'll sweep through some of he other APIs and make the same change to return None instead of a key error.

**Pull request merged**
